### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by LSCNH510072** [program-zoubg/CLangIDE#2]
编译失败

#include <bits/stdc++.h>
using namespace std;
int main() {
    
	
	int n;
	cin>>n;
	cout<<n;
	cout<<n;
	cout<<n;
	cout<<n;
	
    return 0;
}

**Comment by program-zoubg** [comment]
这里编译正常，无法复现，你是下载源代码还是Release版本？源代码版本GCC文件可能有缺失，建议Release版本
![image](https://github.com/program-zoubg/CLangIDE/assets/131129580/aca854cf-7a7e-4e51-9b04-344b0aee1016)

**Comment by program-zoubg** [comment]
已修复源代码TDM文件缺失问题：[Commit #db66c71](https://github.com/program-zoubg/CLangIDE/commit/db66c71ae0c6d79f11be7621c137fd86e1ec4f5d)
